Repository GSG-G11/tecStorm-portfolio, pull requests merged in 2022-01, with the labels that each got.

#11 Adding live link to readme file
  README.md
Labels: Awaiting Review

#12 Creating file structure and adding assest files in assest folder
  assest/abdulrahman.jpg
  assest/hani.jpg
  assest/ibrahim.jpg
  assest/rand.png
  index.html
  style.css
Labels: Approved, Done

#14 Designing the about us section and styling add imgs
  assest/about-us-computer.png
  assest/about-us-ipad.png
  index.html
  style.css
Labels: Done

#15 Footer section desgin
  index.html
  style.css
Labels: Awaiting Review

#16 6 header
  index.html
  style.css
Labels: Approved, Done

#19 fixing styling bug
  style.css
Labels: Approved, Done

#21 Moving svg tag to separte file in assests folder
  assest/storm-logo.svg
  index.html
  style.css
Labels: enhancement

#22 contact us section contact form
  index.html
  style.css
Labels: Approved, Done

#23 adding contact info card
  index.html
  style.css
Labels: Approved, Done

#26 improving style and adding some animation
  index.html
  style.css
Labels: Approved

#27 7 write readme file
  README.md
Labels: Awaiting Review

#24 5-our-team-section
  README.md
  assest/about-us-computer.png
  assest/about-us-ipad.png
  assest/storm-logo.svg
  index.html
  style.css
Labels: Awaiting Review

#28 5 our team section
  assest/hani.jpg
  index.html
  style.css
Labels: Done

#32 29 fix bugs v1
  index.html
  style.css
Labels: Done

#34 fix link to open new tab
  index.html
  style.css
Labels: Awaiting Review, Done
